"""add indexes to vehicle_id date owner_id and nullable mileage

Revision ID: 1d4d1f4a03b1
Revises: 151a27c2a7d2
Create Date: 2026-06-25 15:16:13.034814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4d1f4a03b1'
down_revision: Union[str, Sequence[str], None] = '151a27c2a7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fuel_logs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_fuel_logs_date'), 'fuel_logs', ['date'], unique=False)
    op.create_index(op.f('idx_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('idx_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vehicles_owner_id'), table_name='vehicles')
    op.drop_index(op.f('idx_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.drop_index(op.f('idx_fuel_logs_date'), table_name='fuel_logs')
    op.alter_column('fuel_logs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
