"""create service_logs table

Revision ID: 692ccb379786
Revises: 1d4d1f4a03b1
Create Date: 2026-06-29 15:24:23.519683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '692ccb379786'
down_revision: Union[str, Sequence[str], None] = '1d4d1f4a03b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('service_center', sa.String(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('services_done', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_odometer', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_service_logs_date'), 'service_logs', ['date'], unique=False)
    op.create_index(op.f('idx_service_logs_vehicle_id'), 'service_logs', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_service_logs_vehicle_id'), table_name='service_logs')
    op.drop_index(op.f('idx_service_logs_date'), table_name='service_logs')
    op.drop_table('service_logs')
    # ### end Alembic commands ###
