"""replace single-column indexes with composites

Revision ID: df30a7712012
Revises: af0fae07330e
Create Date: 2026-08-24 12:27:30.009836

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'df30a7712012'
down_revision: Union[str, Sequence[str], None] = 'af0fae07330e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_documents_vehicle_id'), table_name='documents')
    op.create_index('idx_documents_vehicle_id_created_at_id', 'documents', ['vehicle_id', 'created_at', 'id'], unique=False)
    op.create_index('idx_documents_vehicle_id_expiry_date', 'documents', ['vehicle_id', 'expiry_date'], unique=False)
    op.drop_index(op.f('idx_fuel_logs_date'), table_name='fuel_logs')
    op.drop_index(op.f('idx_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.create_index('idx_fuel_logs_vehicle_id_date_id', 'fuel_logs', ['vehicle_id', 'date', 'id'], unique=False)
    op.drop_index(op.f('idx_service_logs_date'), table_name='service_logs')
    op.drop_index(op.f('idx_service_logs_vehicle_id'), table_name='service_logs')
    op.create_index('idx_service_logs_vehicle_id_date_id', 'service_logs', ['vehicle_id', 'date', 'id'], unique=False)
    op.drop_index(op.f('idx_vehicles_owner_id'), table_name='vehicles')
    op.create_index('idx_vehicles_owner_id_created_at_id', 'vehicles', ['owner_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicles_owner_id_created_at_id', table_name='vehicles')
    op.create_index(op.f('idx_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.drop_index('idx_service_logs_vehicle_id_date_id', table_name='service_logs')
    op.create_index(op.f('idx_service_logs_vehicle_id'), 'service_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('idx_service_logs_date'), 'service_logs', ['date'], unique=False)
    op.drop_index('idx_fuel_logs_vehicle_id_date_id', table_name='fuel_logs')
    op.create_index(op.f('idx_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('idx_fuel_logs_date'), 'fuel_logs', ['date'], unique=False)
    op.drop_index('idx_documents_vehicle_id_expiry_date', table_name='documents')
    op.drop_index('idx_documents_vehicle_id_created_at_id', table_name='documents')
    op.create_index(op.f('idx_documents_vehicle_id'), 'documents', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###
